###ID: 6 - Calculate Eigenvalues of a Matrix
Write a Python function that calculates the eigenvalues of a 2x2 matrix. The function should return a list containing the eigenvalues, sort values from highest to lowest.

In [ ]:
import numpy as np
def calculate_eigenvalues(matrix: list[list[float|int]]) -> list[float]:
	eigenvalues, eigenvectors = np.linalg.eig(matrix)
	return list(eigenvalues)

In [ ]:
print(calculate_eigenvalues([[4, -2], [1, 1]]))

[3.0, 2.0]


In [ ]:
def calculate_eigenvalues_manual(matrix: list[list[float|int]]) -> list[float]:
  a, b = matrix[0]
  c, d = matrix[1]

  trace = a + d  # Sum of diagonal elements
  determinant = a * d - b * c  # Determinant of the matrix
  discriminant = (trace ** 2) - (4 * determinant)  # Compute the discriminant

  sqrt_discriminant = discriminant ** 0.5  # Compute square root

  # Compute eigenvalues
  lambda1 = (trace + sqrt_discriminant) / 2
  lambda2 = (trace - sqrt_discriminant) / 2

  return [lambda1, lambda2]  # Sort in descending order

In [ ]:
print(calculate_eigenvalues_manual([[4, -2], [1, 1]]))

[3.0, 2.0]


###ID: 7 - Matrix Transformation
Write a Python function that transforms a given matrix A using the operation $T^{-1} AS$, where T and S are invertible matrices. The function should first validate if the matrices T and S are invertible, and then perform the transformation. In cases where there is no solution return -1

In [ ]:
import numpy as np
from typing import List, Union

def transform_matrix(
    A: list[list[Union[int, float]]],
    T: list[list[Union[int, float]]],
    S: list[list[Union[int, float]]]
) -> list[list[Union[int, float]]]:
    """
    Transforms the matrix A using the operation T^{-1} A S.

    Parameters:
        A: A matrix represented as a list of lists, where each element is int or float.
        T: An invertible square matrix. The number of rows of A must equal the size of T.
        S: An invertible square matrix. The number of columns of A must equal the size of S.

    Returns:
        The transformed matrix as a list of lists if T and S are invertible and dimensions match,
        otherwise returns -1.
    """
    # Validate that T is a non-empty square matrix.
    if not T or any(len(row) != len(T) for row in T):
        return -1

    # Validate that S is a non-empty square matrix.
    if not S or any(len(row) != len(S) for row in S):
        return -1

    # Validate that A has dimensions compatible with T and S.
    if len(A) != len(T) or any(len(row) != len(S) for row in A):
        return -1

    # Convert lists to NumPy arrays for computation.
    T_arr = np.array(T, dtype=float)
    A_arr = np.array(A, dtype=float)
    S_arr = np.array(S, dtype=float)

    # Validate that T is invertible.
    try:
        T_inv = np.linalg.inv(T_arr)
    except np.linalg.LinAlgError:
        return -1

    # Validate that S is invertible (even though we don't use S^{-1} in the transformation).
    try:
        _ = np.linalg.inv(S_arr)
    except np.linalg.LinAlgError:
        return -1

    # Compute the transformation: T^{-1} * A * S.
    result = T_inv @ A_arr @ S_arr

    # Convert the result back to a list of lists.
    return result.tolist()

In [ ]:
A = [[1, 2], [3, 4]]
T = [[2, 0], [0, 2]]
S = [[1, 1], [0, 1]]
print(transform_matrix(A, T, S))

[[0.5, 1.5], [1.5, 3.5]]


###ID: 8 - Calculate 2x2 Matrix Inverse
Write a Python function that calculates the inverse of a 2x2 matrix. Return 'None' if the matrix is not invertible.

In [ ]:
from typing import List
import numpy as np

def inverse_2x2(matrix: List[List[float]]) -> List[List[float]]:
    """
    Computes the inverse of a 2x2 matrix.

    Parameters:
        matrix: A 2x2 matrix represented as a list of lists of floats.

    Returns:
        The inverse of the input matrix as a list of lists if the matrix is invertible,
        otherwise returns -1.
    """
    # Check that the input matrix is non-empty and square (i.e., has the same number of rows and columns).
    if not matrix or any(len(row) != len(matrix) for row in matrix):
        return -1

    # Convert the input list-of-lists into a NumPy array for numerical computation.
    M_arr = np.array(matrix, dtype=float)

    # Attempt to compute the inverse of the matrix using NumPy's linear algebra module.
    # If the matrix is singular (non-invertible), a LinAlgError is raised, and we return -1.
    try:
        M_inv = np.linalg.inv(M_arr)
    except np.linalg.LinAlgError:
        return -1

    # Convert the resulting NumPy array back to a list-of-lists and return it.
    return M_inv.tolist()

In [ ]:
matrix = [[4, 7], [2, 6]]
print(inverse_2x2(matrix))

[[0.6000000000000001, -0.7000000000000001], [-0.2, 0.4]]


###ID: 9 - Matrix times Matrix
Multiply two matrices together (return -1 if shapes of matrix dont aline), i.e. C=A⋅B

In [ ]:
from typing import List
import numpy as np

def matrixmul(A: list[list[int | float]],
              B: list[list[int | float]]) -> list[list[int | float]] | int:
    # Get the dimensions of the matrices
    rows_a, cols_a = len(A), len(A[0]) if A else 0
    rows_b, cols_b = len(B), len(B[0]) if B else 0

    # Check if multiplication is possible
    if cols_a != rows_b:
        return -1  # Matrices are not aligned

    A_arr = np.array(A, dtype=float)
    B_arr = np.array(B, dtype=float)

    # Perform matrix multiplication
    result = A_arr @ B_arr

    return result.tolist()

In [ ]:
print(matrixmul(A = [[1,2],[2,4]], B = [[2,1],[3,4]]))

[[8.0, 9.0], [16.0, 18.0]]


###ID: 11 - Solve Linear Equations using Jacobi Method
Write a Python function that uses the Jacobi method to solve a system of linear equations given by Ax = b. The function should iterate n times, rounding each intermediate solution to four decimal places, and return the approximate solution x.

In [ ]:
import numpy as np

def solve_jacobi(A, b, iterations):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = A.shape[0]
    x = np.zeros(n)

    # Precompute the inverse of the diagonal elements of A
    D_inv = 1 / np.diag(A)
    # Compute the off-diagonal part of A
    R = A - np.diag(np.diag(A))

    for _ in range(iterations):
        # Compute the new x using the Jacobi update formula
        x = D_inv * (b - np.dot(R, x))
        # Round the solution to 4 decimal places after each iteration
        x = np.round(x, 4)

    return x.tolist()

In [ ]:
import numpy as np

def solve_jacobi_(A: np.ndarray, b: np.ndarray, n: int) -> list:
    d_a = np.diag(A)
    nda = A - np.diag(d_a)
    x = np.zeros(len(b))
    x_hold = np.zeros(len(b))
    for _ in range(n):
        for i in range(len(A)):
            x_hold[i] = (1/d_a[i]) * (b[i] - sum(nda[i]*x))
        x = x_hold.copy()
    return np.round(x,4).tolist()

In [ ]:
print(solve_jacobi(np.array([[5, -2, 3], [-3, 9, 1], [2, -1, -7]]), np.array([-1, 2, 3]),2))

[0.146, 0.2032, -0.5175]


###ID: 17 - K-Means Clustering
Your task is to write a Python function that implements the k-Means clustering algorithm. This function should take specific inputs and produce a list of final centroids. k-Means clustering is a method used to partition n points into k clusters. The goal is to group similar points together and represent each group by its center (called the centroid).
Function Inputs:
  * points: A list of points, where each point is a tuple of coordinates (e.g., (x, y) for 2D points)
  * k: An integer representing the number of clusters to form
  * initial_centroids: A list of initial centroid points, each a tuple of coordinates
  * max_iterations: An integer representing the maximum number of iterations to perform

Function Output:

A list of the final centroids of the clusters, where each centroid is rounded to the nearest fourth decimal.

In [ ]:
def k_means_clustering(points, k, initial_centroids, max_iterations):
    centroids = [tuple(centroid) for centroid in initial_centroids]

    for _ in range(max_iterations):
        # Assign each point to the nearest centroid
        clusters = [[] for _ in range(k)]
        for point in points:
            # Calculate squared distances to avoid sqrt for efficiency
            distances = [sum((p - c) ** 2 for p, c in zip(point, centroid)) for centroid in centroids]
            closest = distances.index(min(distances))
            clusters[closest].append(point)

        # Compute new centroids
        new_centroids = []
        for i in range(k):
            cluster_points = clusters[i]
            if cluster_points:
                # Calculate the mean of each coordinate
                sum_coords = [sum(dim) for dim in zip(*cluster_points)]
                avg = tuple(coord_sum / len(cluster_points) for coord_sum in sum_coords)
            else:
                # If no points, keep the previous centroid
                avg = centroids[i]
            new_centroids.append(avg)

        # Check for convergence
        if new_centroids == centroids:
            break
        centroids = new_centroids

    # Round each coordinate of the centroids to the nearest fourth decimal
    rounded_centroids = [tuple(round(coord, 4) for coord in centroid) for centroid in centroids]
    return rounded_centroids

In [ ]:
print(k_means_clustering([(1, 2), (1, 4), (1, 0), (10, 2), (10, 4), (10, 0)], 2, [(1, 1), (10, 1)], 10))
# Expected [(1.0, 2.0), (10.0, 2.0)]

[(1.0, 2.0), (10.0, 2.0)]


###ID: 18 - Cross-Validation Data Split Implementation
Write a Python function that performs k-fold cross-validation data splitting from scratch. The function should take a dataset (as a 2D NumPy array where each row represents a data sample and each column represents a feature) and an integer k representing the number of folds. The function should split the dataset into k parts, systematically use one part as the test set and the remaining as the training set, and return a list where each element is a tuple containing the training set and test set for each fold.

In [ ]:
import numpy as np

def cross_validation_split(data: np.ndarray, k: int, seed=42) -> list:
    np.random.seed(seed)
    n_samples = data.shape[0]
    indices = np.arange(n_samples)
    np.random.shuffle(indices)

    folds = np.array_split(indices, k)
    k_folds = []

    for i in range(k):
        test_indices = folds[i]
        train_indices = np.concatenate([folds[j] for j in range(k) if j != i])
        train_set = data[train_indices].tolist()
        test_set = data[test_indices].tolist()
        k_folds.append((train_set, test_set))

    return k_folds

In [ ]:
print(cross_validation_split(data = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]), k = 5))

[([[9, 10], [5, 6], [1, 2], [7, 8]], [[3, 4]]), ([[3, 4], [5, 6], [1, 2], [7, 8]], [[9, 10]]), ([[3, 4], [9, 10], [1, 2], [7, 8]], [[5, 6]]), ([[3, 4], [9, 10], [5, 6], [7, 8]], [[1, 2]]), ([[3, 4], [9, 10], [5, 6], [1, 2]], [[7, 8]])]


###ID: 19 - Principal Component Analysis (PCA) Implementation
Write a Python function that performs Principal Component Analysis (PCA) from scratch. The function should take a 2D NumPy array as input, where each row represents a data sample and each column represents a feature. The function should standardize the dataset, compute the covariance matrix, find the eigenvalues and eigenvectors, and return the principal components (the eigenvectors corresponding to the largest eigenvalues). The function should also take an integer k as input, representing the number of principal components to return.

Reasoning:
After standardizing the data and computing the covariance matrix, the eigenvalues and eigenvectors are calculated. The largest eigenvalue's corresponding eigenvector is returned as the principal component, rounded to four decimal places.

In [ ]:
import numpy as np

def pca(data: np.ndarray, k: int) -> np.ndarray:
    """
    Performs Principal Component Analysis (PCA) from scratch.
    Args:
        X (numpy.ndarray): A 2D NumPy array where each row is a data sample
                           and each column represents a feature.
        k (int): The number of principal components to return.
    Returns:
        numpy.ndarray: A NumPy array containing the top k principal components
                       (eigenvectors corresponding to the largest eigenvalues).
                       Each row is a principal component.
    """
    # 1. Standardize the dataset
    mean = np.mean(data, axis=0)
    std_dev = np.std(data, axis=0)
    data_standardized = (data - mean) / std_dev

    # 2. Compute the covariance matrix
    covariance_matrix = np.cov(data_standardized.T) # Transpose X_standardized to get features as rows

    # 3. Compute eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)

    # 4. Sort eigenvalues and eigenvectors in descending order of eigenvalues
    eigen_pairs = [(np.abs(eigenvalues[i]), eigenvectors[:, i]) for i in range(len(eigenvalues))]
    eigen_pairs.sort(key=lambda x: x[0], reverse=True)

    # 5. Select top k eigenvectors (principal components)
    principal_components = np.array([pair[1] for pair in eigen_pairs[:k]]).T # Transpose to have PC as rows

    return np.round(principal_components, 4).tolist()

In [ ]:
print(pca(data = np.array([[1, 2], [3, 4], [5, 6]]), k = 1))

[[0.7071], [0.7071]]


###ID: 25 - Single Neuron with Backpropagation
Write a Python function that simulates a single neuron with sigmoid activation, and implements backpropagation to update the neuron's weights and bias. The function should take a list of feature vectors, associated true binary labels, initial weights, initial bias, a learning rate, and the number of epochs. The function should update the weights and bias using gradient descent based on the MSE loss, and return the updated weights, bias, and a list of MSE values for each epoch, each rounded to four decimal places.

In [ ]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def train_neuron(features, labels, initial_weights, initial_bias, learning_rate, epochs):
    weights = np.array(initial_weights, dtype=np.float64)
    bias = np.float64(initial_bias)
    mse_values = []
    num_samples = len(features)

    for _ in range(epochs):
        total_loss = 0.0
        grad_weights = np.zeros_like(weights)
        grad_bias = 0.0

        for x, y in zip(features, labels):
            x_array = np.array(x, dtype=np.float64)
            z = np.dot(weights, x_array) + bias
            a = sigmoid(z)
            loss = (a - y) ** 2
            total_loss += loss

            # Compute gradients
            da = 2 * (a - y)
            dz = da * a * (1 - a)
            dw = dz * x_array
            db = dz

            grad_weights += dw
            grad_bias += db

        # Average the gradients and loss
        avg_loss = total_loss / num_samples
        avg_grad_weights = grad_weights / num_samples
        avg_grad_bias = grad_bias / num_samples

        # Update weights and bias
        weights -= learning_rate * avg_grad_weights
        bias -= learning_rate * avg_grad_bias

        # Record MSE for this epoch
        mse_values.append(round(avg_loss, 4))

    # Round the final parameters to four decimal places
    updated_weights = [round(w, 4) for w in weights]
    updated_bias = round(bias, 4)

    return updated_weights, updated_bias, mse_values

In [ ]:
print(train_neuron(features = [[1.0, 2.0], [2.0, 1.0], [-1.0, -2.0]], labels = [1, 0, 0], initial_weights = [0.1, -0.2], initial_bias = 0.0, learning_rate = 0.1, epochs = 2))

###ID: 26 - Implementing Basic Autograd Operations
Special thanks to Andrej Karpathy for making a video about this, if you haven't already check out his videos on YouTube https://youtu.be/VMj-3S1tku0?si=gjlnFP4o3JRN9dTg. Write a Python class similar to the provided 'Value' class that implements the basic autograd operations: addition, multiplication, and ReLU activation. The class should handle scalar values and should correctly compute gradients for these operations through automatic differentiation.

In [ ]:
class Value:
    def __init__(self, data, _children=(), _op=''):
        self.data = data
        self.grad = 0  # Initialize grad as an integer
        self._backward = lambda: None
        self._prev = set(_children)
        self._op = _op

    def __repr__(self):
        return f"Value(data={self.data}, grad={self.grad})"

    def __add__(self, other):
        other = other if isinstance(other, Value) else Value(other)
        out = Value(self.data + other.data, (self, other), '+')

        def _backward():
            self.grad += int(round(out.grad))  # Round and convert to integer
            other.grad += int(round(out.grad))  # Round and convert to integer
        out._backward = _backward

        return out

    def __mul__(self, other):
        other = other if isinstance(other, Value) else Value(other)
        out = Value(self.data * other.data, (self, other), '*')

        self_data = self.data
        other_data = other.data

        def _backward():
            self.grad += int(round(out.grad * other_data))  # Round and convert to integer
            other.grad += int(round(out.grad * self_data))  # Round and convert to integer
        out._backward = _backward

        return out

    def __radd__(self, other):
        return self + other

    def __rmul__(self, other):
        return self * other

    def relu(self):
        out_data = self.data if self.data > 0 else 0.0
        out = Value(out_data, (self,), 'ReLU')

        derivative = 1.0 if self.data > 0 else 0.0

        def _backward():
            self.grad += int(round(out.grad * derivative))  # Round and convert to integer
        out._backward = _backward

        return out

    def backward(self):
        topo = []
        visited = set()
        def build_topo(v):
            if v not in visited:
                visited.add(v)
                for child in v._prev:
                    build_topo(child)
                topo.append(v)
        build_topo(self)
        topo.reverse()

        self.grad = 1  # Initialize output gradient as an integer
        for node in topo:
            node._backward()

In [ ]:
a = Value(2)
b = Value(-3)
c = Value(10)
d = a + b * c
e = d.relu()
e.backward()
print(a, b, c, d, e)

Value(data=2, grad=0) Value(data=-3, grad=0) Value(data=10, grad=0) Value(data=-28, grad=0) Value(data=0.0, grad=1)


###ID: 31 - Divide Dataset Based on Feature Threshold
Write a Python function to divide a dataset based on whether the value of a specified feature is greater than or equal to a given threshold. The function should return two subsets of the dataset: one with samples that meet the condition and another with samples that do not.


In [ ]:
import numpy as np

def divide_on_feature(X, feature_i, threshold):
    # Create a boolean mask for samples where the feature value is >= threshold
    mask = X[:, feature_i] >= threshold
    # Subset the dataset based on the mask
    meet_condition = X[mask]
    not_meet_condition = X[~mask]
    return meet_condition, not_meet_condition


In [ ]:
X = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8],
              [9, 10]])
feature_i = 0
threshold = 5

print(divide_on_feature(X, feature_i, threshold))

(array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]]), array([[1, 2],
       [3, 4]]))


###ID: 32 - Generate Polynomial Features
Write a Python function to generate polynomial features for a given dataset. The function should take in a 2D numpy array X and an integer degree, and return a new 2D numpy array with polynomial features up to the specified degree.


In [ ]:
import numpy as np
from itertools import combinations_with_replacement

def polynomial_features(X, degree):
    n_samples, n_features = X.shape
    features = []
    # Iterate over degrees 0 to degree (degree 0 corresponds to the constant feature)
    for d in range(degree + 1):
        # Generate all combinations of feature indices with replacement
        for comb in combinations_with_replacement(range(n_features), d):
            if len(comb) == 0:
                # For degree 0, add the constant feature (ones)
                feature = np.ones((n_samples, 1))
            else:
                # Multiply the selected features for the current combination
                feature = np.prod(X[:, comb], axis=1, keepdims=True)
            features.append(feature)
    return np.concatenate(features, axis=1)


In [ ]:
X = np.array([[2, 3],
                  [3, 4],
                  [5, 6]])
degree = 2
print(polynomial_features(X, degree))

[[ 1.  2.  3.  4.  6.  9.]
 [ 1.  3.  4.  9. 12. 16.]
 [ 1.  5.  6. 25. 30. 36.]]


###ID: 33 - Generate Random Subsets of a Dataset
Write a Python function to generate random subsets of a given dataset. The function should take in a 2D numpy array X, a 1D numpy array y, an integer n_subsets, and a boolean replacements. It should return a list of n_subsets random subsets of the dataset, where each subset is a tuple of (X_subset, y_subset). If replacements is True, the subsets should be created with replacements; otherwise, without replacements.



In [ ]:
import numpy as np

def get_random_subsets(X, y, n_subsets, replacements=True, seed=42):
    np.random.seed(seed)
    n_samples = X.shape[0]
    # Use full dataset size for bootstrap (with replacement)
    # Use half the dataset size for subsampling (without replacement)
    subset_size = n_samples if replacements else n_samples // 2
    subsets = []
    for _ in range(n_subsets):
        indices = np.random.choice(n_samples, size=subset_size, replace=replacements)
        X_subset = X[indices].tolist()
        y_subset = y[indices].tolist()
        subsets.append((X_subset, y_subset))
    return subsets


In [ ]:
import numpy as np

def get_random_subsets(X, y, n_subsets, replacements=True, seed=42):
    np.random.seed(seed)

    n, m = X.shape

    subset_size = n if replacements else n // 2
    idx = np.array([np.random.choice(n, subset_size, replace=replacements) for _ in range(n_subsets)])
    # convert all ndarrays to lists
    return [(X[idx][i].tolist(), y[idx][i].tolist()) for i in range(n_subsets)]


In [ ]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y = np.array([1, 2, 3, 4, 5])
print(get_random_subsets(X, y, 3, False, seed=42))

[([[3, 4], [9, 10]], [2, 5]), ([[7, 8], [3, 4]], [4, 2]), ([[3, 4], [1, 2]], [2, 1])]


###ID: 37 - Calculate Correlation Matrix
Write a Python function to calculate the correlation matrix for a given dataset. The function should take in a 2D numpy array X and an optional 2D numpy array Y. If Y is not provided, the function should calculate the correlation matrix of X with itself. It should return the correlation matrix as a 2D numpy array.



In [ ]:
import numpy as np

def calculate_correlation_matrix(X, Y=None):
    if Y is None:
        # Calculate the correlation matrix for X with itself.
        # Set rowvar=False since each column is a variable.
        return np.corrcoef(X, rowvar=False)
    else:
        # Ensure that X and Y have the same number of samples
        if X.shape[0] != Y.shape[0]:
            raise ValueError("X and Y must have the same number of rows (samples).")

        # Calculate means and center the data
        X_mean = np.mean(X, axis=0)
        Y_mean = np.mean(Y, axis=0)
        X_centered = X - X_mean
        Y_centered = Y - Y_mean

        # Compute covariance matrix between columns of X and Y
        cov_matrix = np.dot(X_centered.T, Y_centered) / (X.shape[0] - 1)

        # Compute standard deviations (using ddof=1 for sample std)
        X_std = np.std(X, axis=0, ddof=1)
        Y_std = np.std(Y, axis=0, ddof=1)

        # Compute correlation matrix by dividing covariance by the outer product of stds
        corr_matrix = cov_matrix / np.outer(X_std, Y_std)
        return corr_matrix


In [ ]:
X = np.array([[1, 2], [3, 4], [5, 6]])
print("Correlation matrix for X with itself:")
print(calculate_correlation_matrix(X))

# Correlation between X and Y
Y = np.array([[2, 1], [4, 3], [6, 5]])
print("\nCorrelation matrix between X and Y:")
print(calculate_correlation_matrix(X, Y))

Correlation matrix for X with itself:
[[1. 1.]
 [1. 1.]]

Correlation matrix between X and Y:
[[1. 1.]
 [1. 1.]]


###ID: 41 - Simple Convolutional 2D Layer
In this problem, you need to implement a 2D convolutional layer in Python. This function will process an input matrix using a specified convolutional kernel, padding, and stride.


In [ ]:
import numpy as np

def simple_conv2d(input_matrix: np.ndarray, kernel: np.ndarray, padding: int, stride: int):
    input_height, input_width = input_matrix.shape
    kernel_height, kernel_width = kernel.shape

    # Pad the input matrix with zeros
    padded_input = np.pad(input_matrix,
                          pad_width=((padding, padding), (padding, padding)),
                          mode='constant',
                          constant_values=0)

    # Calculate output dimensions
    output_height = (input_height + 2 * padding - kernel_height) // stride + 1
    output_width = (input_width + 2 * padding - kernel_width) // stride + 1
    output_matrix = np.zeros((output_height, output_width))

    # Perform the convolution
    for i in range(output_height):
        for j in range(output_width):
            h_start = i * stride
            h_end = h_start + kernel_height
            w_start = j * stride
            w_end = w_start + kernel_width

            # Extract the region of interest
            region = padded_input[h_start:h_end, w_start:w_end]
            output_matrix[i, j] = np.sum(region * kernel)

    return output_matrix


In [ ]:
input_matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

kernel = np.array([
    [1, 0],
    [-1, 1]
])

padding = 1
stride = 2

output = simple_conv2d(input_matrix, kernel, padding, stride)
print(output)

[[ 1.  1. -4.]
 [ 9.  7. -4.]
 [ 0. 14. 16.]]


###ID: 47 - Implement Gradient Descent Variants with MSE Loss
In this problem, you need to implement a single function that can perform three variants of gradient descent [€”Stochastic Gradient Descent (SGD), Batch Gradient Descent, and Mini-Batch Gradient Descent]€  ”using Mean Squared Error (MSE) as the loss function. The function will take an additional parameter to specify which variant to use.

In [1]:
import numpy as np

def gradient_descent(X, y, weights, learning_rate, n_iterations, batch_size=1, method='batch'):
    m = len(y)

    for _ in range(n_iterations):
        if method == 'batch':
            # Calculate the gradient using all data points
            predictions = X.dot(weights)
            errors = predictions - y
            gradient = 2 * X.T.dot(errors) / m
            weights = weights - learning_rate * gradient

        elif method == 'stochastic':
            # Update weights for each data point individually
            for i in range(m):
                prediction = X[i].dot(weights)
                error = prediction - y[i]
                gradient = 2 * X[i].T.dot(error)
                weights = weights - learning_rate * gradient

        elif method == 'mini_batch':
            # Update weights using sequential batches of data points without shuffling
            for i in range(0, m, batch_size):
                X_batch = X[i:i+batch_size]
                y_batch = y[i:i+batch_size]
                predictions = X_batch.dot(weights)
                errors = predictions - y_batch
                gradient = 2 * X_batch.T.dot(errors) / batch_size
                weights = weights - learning_rate * gradient

    return weights


In [4]:
import numpy as np

# Sample data
X = np.array([[1, 1], [2, 1], [3, 1], [4, 1]])
y = np.array([2, 3, 4, 5])

# Parameters
learning_rate = 0.01
n_iterations = 1000
batch_size = 2

# Initialize weights
weights = np.zeros(X.shape[1])

# Test Batch Gradient Descent
print(gradient_descent(X, y, weights, learning_rate, n_iterations, method='batch'))
# Test Stochastic Gradient Descent
print(gradient_descent(X, y, weights, learning_rate, n_iterations, method='stochastic'))
# Test Mini-Batch Gradient Descent
print(gradient_descent(X, y, weights, learning_rate, n_iterations, batch_size, method='mini_batch'))

[1.01003164 0.97050576]
[1.00910568 0.9767164 ]
[1.0100837  0.97053393]


###ID: 48 - Implement Reduced Row Echelon Form (RREF) Function
In this problem, your task is to implement a function that converts a given matrix into its Reduced Row Echelon Form (RREF). The RREF of a matrix is a special form where each leading entry in a row is 1, and all other elements in the column containing the leading 1 are zeros, except for the leading 1 itself.

However, there are some additional details to keep in mind:

* Diagonal entries can be 0 if the matrix is reducible (i.e., the row corresponding to that position can be eliminated entirely).
* Some rows may consist entirely of zeros.
* If a column contains a pivot (a leading 1), all other entries in that column should be zero.

Your task is to implement the RREF algorithm, which must handle these cases and convert any given matrix into its RREF.

In [6]:
import numpy as np

def rref(matrix, tol=1e-10):
    A = matrix.astype(np.float64).copy()  # work on a float copy
    rows, cols = A.shape
    pivot_row = 0

    for col in range(cols):
        # --- Partial pivoting ---
        # Find the row with the largest absolute value in the current column (from pivot_row onward)
        max_index = None
        max_val = tol
        for r in range(pivot_row, rows):
            if abs(A[r, col]) > max_val:
                max_val = abs(A[r, col])
                max_index = r
        if max_index is None:
            continue  # no suitable pivot in this column

        # Swap to put the best pivot row in position
        if max_index != pivot_row:
            A[[pivot_row, max_index]] = A[[max_index, pivot_row]]

        # --- Normalize pivot row ---
        pivot_val = A[pivot_row, col]
        A[pivot_row, :] = A[pivot_row, :] / pivot_val

        # --- Eliminate all other entries in this column ---
        for r in range(rows):
            if r != pivot_row:
                factor = A[r, col]
                A[r, :] = A[r, :] - factor * A[pivot_row, :]

        pivot_row += 1
        if pivot_row == rows:
            break

    # --- Post-processing: zero out tiny values ---
    A[np.abs(A) < tol] = 0
    return A


In [7]:
import numpy as np

matrix = np.array([
    [1, 2, -1, -4],
    [2, 3, -1, -11],
    [-2, 0, -3, 22]
])

rref_matrix = rref(matrix)
print(rref_matrix)

[[ 1.  0.  0. -8.]
 [ 0.  1.  0.  1.]
 [ 0.  0.  1. -2.]]


###ID: 77 - Calculate Performance Metrics for a Classification Model
In this task, you are required to implement a function performance_metrics(actual, predicted) that computes various performance metrics for a binary classification problem. These metrics include:

* Confusion Matrix
* Accuracy
* F1 Score
* Specificity
* Negative Predictive Value

The function should take in two lists:

* actual: The actual class labels (1 for positive, 0 for negative).
* predicted: The predicted class labels from the model.

**Output**

The function should return a tuple containing:

* confusion_matrix: A 2x2 matrix.
* accuracy: A float representing the accuracy of the model.
* f1_score: A float representing the F1 score of the model.
* specificity: A float representing the specificity of the model.
* negative_predictive_value: A float representing the negative predictive value.

**Constraints**

* All elements in the actual and predicted lists must be either 0 or 1.
* Both lists must have the same length.


In [9]:
def performance_metrics(actual: list[int], predicted: list[int]) -> tuple:
    if len(actual) != len(predicted):
        raise ValueError("The actual and predicted lists must have the same length.")

    # Initialize confusion counts
    TP = FN = FP = TN = 0
    for a, p in zip(actual, predicted):
        if a not in (0, 1) or p not in (0, 1):
            raise ValueError("All elements in actual and predicted must be 0 or 1.")
        if a == 1 and p == 1:
            TP += 1
        elif a == 1 and p == 0:
            FN += 1
        elif a == 0 and p == 1:
            FP += 1
        elif a == 0 and p == 0:
            TN += 1

    confusion_matrix = [[TP, FN], [FP, TN]]
    accuracy = (TP + TN) / len(actual)
    f1 = (2 * TP) / (2 * TP + FP + FN) if (2 * TP + FP + FN) != 0 else 0.0
    specificity = TN / (TN + FP) if (TN + FP) != 0 else 0.0
    negativePredictive = TN / (TN + FN) if (TN + FN) != 0 else 0.0

    return confusion_matrix, round(accuracy, 3), round(f1, 3), round(specificity, 3), round(negativePredictive, 3)


In [10]:
actual = [1, 0, 1, 0, 1]
predicted = [1, 0, 0, 1, 1]
print(performance_metrics(actual, predicted))

([[2, 1], [1, 1]], 0.6, 0.667, 0.5, 0.5)


###ID: 92 - Linear Regression - Power Grid Optimization

It is the year 2157. Mars has its first thriving colony, and energy consumption is steadily on the rise. As the lead data scientist, you have daily power usage measurements (10 days) affected by both a growing linear trend and a daily fluctuation. The fluctuation follows the formula 10 x sin(2pi€ x i / 10), where i is the day number (1 through 10). Your challenge is to remove this known fluctuation from each data point, fit a linear regression model to the detrended data, predict day 15's base consumption, add back the fluctuation for day 15, and finally include a 5% safety margin. The final answer must be an integer, ensuring you meet the colony's future needs.

**Reasoning:**

For each of the 10 days, we subtract the daily fluctuation given by 10xsin(2πxi/10). We then perform linear regression on the resulting values, predict day 15’s base usage, and add back the day 15 fluctuation. Finally, we apply a 5% margin. Running the provided solution code yields 404 for this dataset.

In [69]:
import math
import numpy as np
from scipy import stats

PI = 3.14159

def power_grid_forecast(consumption_data):
    # 1) Subtract the daily fluctuation from each data point.
    detrended_consum = np.array([
        daily_consum - (10 * math.sin(2 * PI * (i + 1) / 10))
        for i, daily_consum in enumerate(consumption_data)
    ]).reshape(-1, 1)

    # 2) Prepare the design matrix for linear regression.
    idxs = np.arange(1, len(consumption_data) + 1).reshape(-1, 1)
    idxs_b = np.c_[np.ones((len(idxs), 1)), idxs]  # Design matrix with intercept term

    # Correct the regression formula:
    # theta = (X^T X)^{-1} X^T y, where X is idxs_b.
    theta = np.linalg.inv(idxs_b.T @ idxs_b) @ idxs_b.T @ detrended_consum

    # 3) Predict day 15's base consumption.
    pred_15 = theta[0] + theta[1] * 15

    # 4) Add the day 15 fluctuation back.
    data_15_fluctuation = pred_15 + (10 * math.sin(2 * PI * 15 / 10))

    # 5) Round, then add a 5% safety margin (rounded up).
    data_15_margin = math.ceil(data_15_fluctuation[0] * 1.05)

    # 6) Return the final integer.
    return data_15_margin


In [70]:
# Example usage:
consumption_data = [150, 165, 185, 195, 210, 225, 240, 260, 275, 290]
print(power_grid_forecast(consumption_data))

404
